### PR TITLE
Fix build and compilation errors

### PR DESCRIPTION
**Pull request by gburca**

### CODE REVIEW

**Comment by v00d00** [comment]
Gabriel you are like santa, bringing lovely pull requests as I sleep...

🎄 🎅

**Comment by gburca** [comment]
I was trying to test the fix for issue #6. I'm not a cmake expert. Perhaps there's a better way to handle the search for alternate lib names.  On my system `pkg-config --libs libupnp` comes back with `-pthread -lupnp4 -lthreadutil4 -lixml4`. Would be nice if those can be fed directly to `find_library()`, but in the mean time this works.

**Comment by v00d00** [comment]
So based on your comment I assume you are using the debian package? I am running against the latest from https://github.com/mrjimenez/pupnp, maybe that is making the difference?

It also explains the compilation errors

**Comment by gburca** [comment]
I'm running on Ubuntu 14.04 LTS, with the default upnp.

My `/usr/include/upnp/FileInfo.h` has:
```
EXPORT_SPEC void UpnpFileInfo_set_LastModified(UpnpFileInfo *p, const time_t *t);
```

It looks like the macro in the latest `pupnp` might not expand to the same function signature. See: https://github.com/mrjimenez/pupnp/commit/2616d4c76ac09ba8217fbf9817dcc45ccf1ba975

Looks like the 2nd arg will need to be modified at compile time to match the upnp version mediatomb is being built against. Or force a minimum upnp version? When building on my system, cmake reports:

```
-- Checking for module 'libupnp'
--   Found libupnp, version 1.8.0~svn20100401
-- Found the upnp libraries at 
-- Found the upnp headers at /usr/include
```

I assumed that matched your v1.8 of upnp. I guess it doesn't.

**Comment by v00d00** [comment]
I think we can to that conclusion at the same time, I've added a check for version and the debian snapshot into CMake and will go through and ifdef where needed.

**Pull request merged**
